name: AKS Create Workflow

on:
  workflow_dispatch: # Allows manual triggering of this workflow
  push:
    tags:
      - 'infra-*' # Trigger only on tags prefixed with 'infra-'

jobs:
  aks-create:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run AKS Creation Script
      run: |
        chmod +x ./path/to/your/aks-create-script.sh
        ./path/to/your/aks-create-script.sh
