apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app
  namespace: demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
      - name: my-nodejs-app
        image: ashokdevop/my-nodejs-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-nodejs-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
